### ISSUE TITLE
Error when never setting "now"

### ISSUE THREAD

**Issue by UweKeim** [studio24/rotate#1]
[This line](https://github.com/studio24/rotate/blob/master/src/Delete.php#L171) reads:

```php
$oldestDate = clone $this->now;
```

When I use the `Delete` class this way:

```php
$logDelete = new studio24\Rotate\Delete($loggerDir . '/*.txt');
$logDelete->deleteByFileModifiedDate('7 days');
```

I get a null reference error on the `clone $this->now;`

Instead I have to do it this way:

```php
$logDelete = new studio24\Rotate\Delete($loggerDir . '/*.txt');
$logDelete->setNow($logDelete->getNow());
$logDelete->deleteByFileModifiedDate('7 days');
```

**My suggestion:**

Please use internally always the call to `getNow()` instead of directly accessing `now`, since `getNow()` sets a default value if nothing is yet configured.

**Comment by simonrjones** [comment]
thanks - sorry for the very long time to respond. Fixed.
